# Generated by Django 3.0.4 on 2020-04-04 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('summarizer_app', '0003_auto_20200404_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_received',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfileInfo'),
        ),
    ]
