# Generated by Django 3.0.4 on 2020-04-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer_app', '0004_auto_20200404_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmer',
            name='language',
        ),
        migrations.DeleteModel(
            name='languages',
        ),
        migrations.DeleteModel(
            name='Paradigm',
        ),
        migrations.DeleteModel(
            name='Programmer',
        ),
    ]
