# Generated by Django 3.0.4 on 2020-04-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer_app', '0006_auto_20200410_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_received',
            name='image',
            field=models.FileField(upload_to='photos_to_summarize'),
        ),
    ]
