# Generated by Django 3.0.4 on 2020-04-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer_app', '0008_auto_20200410_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_received',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos_to_summarize'),
        ),
    ]
