# Generated by Django 3.0.4 on 2020-04-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer_app', '0012_auto_20200419_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_received',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos_to_summarize/%d-%m-%Y/'),
        ),
    ]
