# Generated by Django 3.0.4 on 2020-04-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='image',
            new_name='Profile_image',
        ),
    ]
