# Generated by Django 3.0.4 on 2020-04-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200409_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='Profile_image',
            field=models.ImageField(default='media/default.jpg', upload_to='profile_pics'),
        ),
    ]
